import os
import re

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    lib_src_dir = os.path.join(base_dir, "lib/src")
    
    styles = {
        "bold": ("IconsaxBold", "IconData"),
        "broken": ("IconsaxBroken", "IconData"),
        "bulk": ("IconsaxBulk", "IconsaxIconData"),
        "linear": ("IconsaxLinear", "IconData"),
        "outline": ("IconsaxOutline", "IconData"),
        "twotone": ("IconsaxTwotone", "IconsaxIconData")
    }
    
    registry_content = []
    registry_content.append("// Generated by scripts/generate_example_registry.py. Do not edit manually.")
    registry_content.append("import 'package:flutter/widgets.dart';")
    registry_content.append("import 'package:iconsax/iconsax.dart';")
    registry_content.append("")
    
    # Regex to match: static const IconData name = ... OR static const IconsaxIconData name = ...
    pattern = re.compile(r"static\s+const\s+(IconData|IconsaxIconData)\s+(\w+)\s*=")
    
    for style, (class_name, type_name) in styles.items():
        file_path = os.path.join(lib_src_dir, f"iconsax_{style}.dart")
        if not os.path.exists(file_path):
            print(f"Error: {file_path} does not exist.")
            continue
            
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
            
        matches = pattern.findall(content)
        print(f"Found {len(matches)} icons for style '{style}' (Class: {class_name}, Type: {type_name})")
        
        registry_content.append(f"final Map<String, {type_name}> {style}Icons = {{")
        for match_type, name in matches:
            registry_content.append(f"  '{name}': {class_name}.{name},")
        registry_content.append("};")
        registry_content.append("")
        
    example_lib_dir = os.path.join(base_dir, "example/lib")
    os.makedirs(example_lib_dir, exist_ok=True)
    
    out_path = os.path.join(example_lib_dir, "icon_registry.dart")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(registry_content))
        
    print(f"Successfully generated registry at {out_path}")

if __name__ == "__main__":
    main()
